spring:
  datasource:
    url: jdbc:h2:mem:mockdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS admin\;CREATE SCHEMA IF NOT EXISTS translation\;CREATE SCHEMA IF NOT EXISTS content\;CREATE SCHEMA IF NOT EXISTS registry\;CREATE SCHEMA IF NOT EXISTS publishing\;CREATE SCHEMA IF NOT EXISTS system\;CREATE SCHEMA IF NOT EXISTS migration\;CREATE DOMAIN IF NOT EXISTS jsonb AS json\;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

# For local development without auth
miotranslate:
  auth:
    enabled: false
